const details = {
	code: 0,
	message: "Genres Fetched Successfully",
	data: [
		{
			genre: "Dance",
			events: [
				{
					id: 1,
					genre: "Dance",
					name: "Centrifuge",
					tagline: "Group Dance Competition",
					writeup:
						"Unite your crew, harmonize your steps, and light up the stage with your collective energy. From electrifying Bollywood medleys to compelling thematic acts, display your teamwork, precision, and artistic flair in a stunning showcase of group dance dynamics. Let your creativity take center stage as you captivate the audience with synchronized moves, engaging storytelling, and a vibrant blend of diverse dance styles!",
					min_participation: 3,
					max_participation: 30,
					rules: [
						"1. Mail the audio and list of props at dance.sf2025@gmail.com with the subject “Centrifuge Audio: <College Name>”.",
						"2. Participants should also get their submitted audios on a pen drive or their mobile phone. Live music is not allowed.",
						"3. Stage specification - Area will be approximately 20ft x 25ft.",
						"4. In case of malfunctioning of any equipment provided, the participant will be allowed to repeat the performance from the beginning or from the point of disruption that the participant wishes, with the consent of the judges.",
						"5.  Accessories, costumes and props will have to be arranged by the participants.",
						"6.  List of props to be used should be submitted along with the audio.",
						"7. JUDGING CRITERIA:\n Synchronization and Coordination (40 points)\n Choreography and Creativity (30 points)\n Artistic Presentation (30 points)",
					],
					is_group: true,
					event_status: true,
					latitude: "22 N",
					longitude: "66 E",
					score: 1,
				},
				{
					id: 61,
					genre: "Dance",
					name: "Shuffle - Team ",
					tagline: "Street Dance Competition",
					writeup:
						"The Street dance competition. Have you got what it takes to sweep the crowd off\\nits feet? Your style be hip-hop, tutting, crumping, breakdancing, stepping, b-boying,\\ncontraption or western freestyle dancing, this is your chance to take over the street stage. Team size: 3-20. ",
					min_participation: 3,
					max_participation: 20,
					rules: [
						"Prelims: Showcase Round",
						"1. Dancers will be called to perform one by one in front of the judges.",
						"2. Top scorers will be marked and announced by the judges at the end.",
						"3. Accessories, costumes and props will have to be arranged by the participants.",
						"4. Top 16 teams/individuals will be chosen from this round.\n Pre-finals (Top 16)\nTeams qualifying for this round will be going against each other in a face-off competition. The order of the teams will be decided through a draw system and the battles would be as follows:",
						"1. The music tracks will be provided by the Spring Fest Team on the venue itself.",
						"2. Same music will be provided to both the performaces in a round.",
						"3. Each Battle will be in FIVE rounds for Team Event and in THREE rounds for Solo Event. For the team event, in each round, maximum 4 members from each team can go one after the other.",
						"4. The time limit for each round is 1 minute per team (Music on to Music off) i.e. 1 minute x 2 teams x 5 rounds = Total of 10 minutes for each battle.",
						"5. The time limit for each round is 1 minute per individual (Music on to Music off) i.e. 1 minute x 2 performers x 3 rounds = Total of 6 minutes for each battle.",
						"6. In case of a tie an extra round may be provided.\n Finals (Top 4)\nTeams qualifying for this round will be going against each other in a face-off competition. The order of the teams will be decided through a draw system and the battles would be as follows:",
						"1. The music tracks will be provided by the Spring Fest Team on the venue itself.",
						"2. Same music will be provided to both the teams.",
						"3. Each Battle will be in FIVE rounds. In each round, maximum 4 members from each team can go one\n after the other.",
						"4. The time limit for each round is 1 minute per team (Music on to Music off) i.e. 1 minute x 2 teams x 5 rounds = Total of 10 minutes for each battle.",
						"6. In case of a tie an extra round may be provided.\n JUDGING CRITERIA:\n Musicality \n Foundation\n Foundation\n Difficulty of movement \n Style and Execution\n Composition of Round\n Originality\n Crowd Response\n Dominance over Opposite team\n PRE FINALS: \nOne on One Battle between 16 teams (8 Battles) gives 8 Winners.\nOne on One Battle between 8 winners (4 Knockout Rounds) gives 4 Finalists\n FINALS:\nOne on One Battle Between Finalists Gives Two Winning Battle Teams.\nFinal Battle Between Winning Battle Teams gives Winner.",
					],
					is_group: true,
					event_status: true,
					latitude: "22 N",
					longitude: "66 E",
					score: 1,
				},
				{
					id: 5,
					genre: "Dance",
					name: "Two For A Tango",
					tagline: "Duet Dance competition",
					writeup:
						"Pair up and dance in harmony! Join our duet dance competition, where your\nsynchronized moves and chemistry with your partner create an enchanting\nperformance that steals the spotlight.",
					min_participation: 2,
					max_participation: 2,
					rules: [
						"1. The time limit for the overall performance is 5 minutes exceeding which by 1 minute will lead to disqualification.",
						"2. Participants should also get their submitted audios on a pen drive or their mobile phone. Live music is not allowed.",
						"3. The event is strictly a duo dance competition and there shouldn't be any extra person on stage at any point during the performance.",
						"4. Any dance form is allowed.",
						"5. Accessories, costumes and props will have to be arranged by the participants.",
						"6. Participants should get their songs/music in a pen-drive. Live music is not allowed.",
						"7. Judging criteria includes:\n A. Synchronisation and partnering (40 points)\n B. Emotional expression and chemistry (30 points)\n C. Choreography and artistry (30 points)\n The judges' collective scores across these categories will determine the final outcome of the competition",
						"8. Any combination of two people irrespective of gender is allowed.",
						"9. Stage specification - Area will be approximately 20ft x 25ft.",
						"10. In case of malfunctioning of any equipment provided, the team will be allowed to repeat their performance from the beginning or from the point of disruption that the team wishes, with the consent of the judges.",
						"11. Mail the audio at dance.sf2025@gmail.com with the subject “Two for a Tango Audio: <Participant 1>, <SFID1>, <Participant 2>, <SFID2>”.",
					],
					is_group: true,
					event_status: true,
					latitude: "22 N",
					longitude: "66 E",
					score: 1,
				},
				{
					id: 2,
					genre: "Dance",
					name: "Nrityakala",
					tagline: "Solo Classical Dance Competition",
					writeup:
						"Immerse yourself in the vibrant legacy of Indian classical dance, whether it’s Bharatanatyam, Kathak, Odissi, Kuchipudi, or any other form. Demonstrate your flawless technique, expressive storytelling, and intricate artistry through graceful movements, gestures, and rhythmic footwork. Transform the stage into a canvas of tradition and tales, captivating the audience with the elegance and charm of classical dance!",
					min_participation: 1,
					max_participation: 1,
					rules: [
						"1. The time limit for the overall performance is 5 minutes exceeding which by 1 minute will lead to disqualification.",
						"2. Participants should also get their submitted audios on a pen drive or their mobile phone. Live music is not allowed.",
						"3. The event is strictly a duo dance competition and there shouldn't be any extra person on stage at any point during the performance.",
						"4. Any dance form is allowed.",
						"5. Accessories, costumes and props will have to be arranged by the participants.",
						"6. Participants should get their songs/music in a pen-drive. Live music is not allowed.",
						"7. Judging criteria includes:\n A. Synchronisation and partnering (40 points)\n B. Emotional expression and chemistry (30 points)\n C. Choreography and artistry (30 points)\n The judges' collective scores across these categories will determine the final outcome of the competition",
						"8. Winners get a chance to grab a direct spot in Two for a Tango during the main fest.",
						"9. Any combination of two people irrespective of gender is allowed.",
						"10. Stage specification - Area will be approximately 20ft x 25ft.",
						"11. In case of malfunctioning of any equipment provided, the team will be allowed to repeat their performance from the beginning or from the point of disruption that the team wishes, with the consent of the judge.",
					],
					is_group: false,
					event_status: true,
					latitude: "22 N",
					longitude: "66 E",
					score: 1,
				},
				{
					id: 3,
					genre: "Dance",
					name: "Shake A Leg",
					tagline: "Solo Western Dance Competition",
					writeup:
						"Step into the spotlight alone and let your dance tell a unique story. Showcase your skill and style in our solo dance competition, where your individual artistry takes center stage, captivating hearts with every graceful movement.",
					min_participation: 1,
					max_participation: 1,
					rules: [
						"1. Participants should get their songs/music in a pen-drive. Live music is not allowed.",
						"2. Time limit is 4 minutes (music on to music off) exceeding which by 1 minute will lead to disqualification.",
						"3. In case of malfunctioning of any equipment provided, the participant will be allowed to repeat the performance from the beginning or from the point of disruption that the participant wishes, with the consent of the judges.",
						"4. Accessories, costumes and props have to be arranged by the participants.",
						"5. Judging criteria includes:\n A. choreography (35 points)\n B. Emotion and Attitude (40 points)\n C. Stage utilisation and crowd response (25 points)\n The judges' collective scores across these categories will determine the final outcome of the competition",
					],
					is_group: false,
					event_status: true,
					latitude: "22 N",
					longitude: "66 E",
					score: 1,
				},
				{
					id: 4,
					genre: "Dance",
					name: "Shuffle - Solo",
					tagline: "Street Dance Competition",
					writeup:
						"The nationwide street dance competition. Have you got what it takes to sweep the crowd off\nits feet? Your style be hip-hop, tutting, crumping, breakdancing, stepping, b-boying,\ncontraption or western freestyle dancing, this is your chance to take over the street stage.\nTeam size — min 4 and max 10. Props are not allowed.",
					min_participation: 1,
					max_participation: 1,
					rules: [
						"Prelims",
						"1. The time limit is 4 min to 6 min (length of the music track).",
						"2. Dancers will be called to perform one by one in front of the judges.",
						"3. Top scorers will be marked and announced by the judges at the end.",
						"4. .Accessories, costumes and props will have to be arranged by the participants.",
						"5. Top 16 teams/individuals will be chosen from this round.\n Pre-finals",
						"1. The music tracks will be provided by the Spring Fest Team on the venue itself.",
						"2. Same music will be provided to both the performaces in a round.",
						"3. Each Battle will be in FIVE rounds for Team Event and in THREE rounds for Solo Event. For the team event, in each round, maximum 4 members from each team can go one after the other.",
						"4. The time limit for each round is 1 minute per individual (Music on to Music off) i.e. 1 minute x 2 performers x 3 rounds = Total of 6 minutes for each battle.",
						"5. The teams cannot repeat the performance of the prelims.",
						"6. In case of a tie an extra round may be provided.\n Finals",
						"1. The teams ranked in the top 4 in the pre-finals will compete in the finals. Teams\n qualifying for this round will be going against each other in a face-off competition.\n The order of the teams will be decided through a draw system and the battles\n would be as follows:\n a. Battle 1: Team 1 vs. Team 2\n b. Battle 2: Team 3 vs. Team 4\n c. Final Battle: Winner Battle 1 vs. Winner Battle 2\n d. 3rd Position Battle: Runner-up Battle 1 vs. Runner-up Battle 2",
						"2. The music tracks will be provided by the Spring Fest Team on the venue itself.",
						"3. SAME MUSIC WILL BE PROVIDED TO BOTH THE TEAM.",
						"4. Each Battle will be in FIVE rounds. In each round, maximum 4 members from\n each team can go one after the other.",
						"5. The time limit for each round is 1 min per team (music on to music off) i.e. 1\n min x 2 teams x 5 rounds = Total of 10 minutes for each battle.",
						"6. In case of a tie an extra round may be provided.",
						"7. Judging criteria: · Musicality · Foundation  · Character · Difficulty of movement · Style and Execution ·\n Composition of Round  · Originality · Crowd Response · Dominance over Opposite team ·\n For the FACE-OFF round, crowd support\n and most of all, overshadowing the opposite team will be important factors.",
						"8.The performance should be in cohesion with the integrity of the fest. The songs selected by the\n participants must not contain any foul language. Violation of any of the above will lead to immediate disqualification.\n The decision of the judges will be final and binding. The organizing committee reserves the\n right to make any last minute change in the rules.",
					],
					is_group: false,
					event_status: true,
					latitude: "22 N",
					longitude: "66 E",
					score: 1,
				},
			],
		},
		{
			genre: "Music",
			events: [
				{
					id: 8,
					genre: "Music",
					name: "Can You Duet",
					tagline: "DUET SINGING COMPETITION",
					writeup:
						"Dynamic duos, it’s your time to shine! Step into the spotlight and bring your harmonies to life in an electrifying duet singing competition. With a vibrant atmosphere setting the stage, this is your chance to showcase your chemistry, captivate the audience, and create unforgettable musical magic. Let your voices blend, your energy inspire, and your talent leave a lasting impression on this grand stage!.",
					min_participation: 2,
					max_participation: 2,
					rules: [
						"",
						"1. Time limit: 5 minutes",
						"2. Participants can perform any number of songs (in Hindi, English or both) within the time limit",
						"3. Both the Participants can perform with one instrumental accompaniment or with a backing track but the judging will be done solely on the basis of vocal performance.",
						"4. .Performers can be disqualified on the spot for misconduct, obscenity or foul language.",
						"5. Judging criteria includes:\n\n A. Vocal Excellence (40 points)\n\n B. Performance and Expression (30 points)\n\n C. Overall Presentation (30 points)\n\n The judges' collective scores across these categories will determine the final outcome of the competition.",
					],
					is_group: true,
					event_status: true,
					latitude: "22 N",
					longitude: "66 E",
					score: 1,
				},
				{
					id: 9,
					genre: "Music",
					name: "Rapmania",
					tagline: "Solo Rapping Competition",
					writeup:
						"Ready to spit fire and own the mic? Step up to our rapping competition,\nwhere your lyrical flow and authentic style take center stage, showcasing\nyour passion and paving the way for rap supremacy!",
					min_participation: 1,
					max_participation: 1,
					rules: [
						"1. The first round will be a showcase round from which top 8 participants will be chosen by the judges.",
						"2. Time limit for this performance is 5 minutes, inclusive of setup time.",
						"3. Participants can either opt for a beatboxer along with them or can bring their beats/rhythm for rap along with them on a pen drive or mobile phone.",
						"4. The next round will be among the top 8 participants and the winners of Hitch Hike where in rappers shall be given a theme/topic and 30 minutes to prepare a write-up on the topic before they perform.",
						"5. A common beat shall be given to all the rappers for their performance.",
						"6. Top 2 participants from this round will be promoted to a final round which will be a roast battle between them.",
						"7. Rules and criteria for this battle will be decided by the judges and announced on the spot.",
						"8. Any sort of racist, sexist or offensive slurs will lead to immediate disqualification",
						"9. Judging criteria includes:\n A. Lyricism and content (40 points)\n B. Delivery and flow (30 points)\n C. Stage presence and audience engagement (30 points)\n The judges' collective scores across these categories will determine the final outcome of the competition.",
					],
					is_group: false,
					event_status: true,
					latitude: "22 N",
					longitude: "66 E",
					score: 1,
				},
				{
					id: 54,
					genre: "Music",
					name: "War of The DJs",
					tagline: "DJ WAR",
					writeup:
						"An event for all the DJs out there to showcase their skills, creativity, and technical prowess in a headto-head battle, demonstrating their ability to mix music, scratch, blend tracks, and engage the audience while showcasing their unique style and talent.",
					min_participation: 1,
					max_participation: 1,
					rules: [
						"",
						"1. Time limit: 15 minutes (excluding 5 minutes set-up time)",
						"2. The event will take place in one round.",
						"3. If any participant crosses the given time limit, penalties will be given by the judges accordingly.",
						"4. At least three different genres of music should be used. Language is not a barrier.",
						"5. The participant should play at least six songs and should change at least 4 tracks.",
						"6. Tags can attract negative points and should be avoided.",
						"7. All the required DJ equipment will be provided by us",
						"8. Inappropriate content, religious blasphemy, and vulgarity will not be tolerated.",
						"9. Participants should have their own music. No music will be provided by the organizers.",
						"10. Props or costumes, if used, should be arranged by the participants.",
						"11. PObscenity in any form is strictly prohibited and will result in disqualification.",
						"12. Judging criteria includes:\n\n A. Mixing Techniques and Tricks(40 points)\n\n B. Use of Equipment and Track Selection (30 points)\n\n C. Style Statement, Crowd Engagement and Overall Impact (30 points)\n\n The judges' collective scores across these categories will determine the final outcome of the competition.",
					],
					is_group: false,
					event_status: true,
					latitude: "22 N",
					longitude: "66 E",
					score: 1,
				},
				{
					id: 13,
					genre: "Music",
					name: "Wildfire",
					tagline: "Nationwide Western Rock Band Competition",
					writeup:
						"Wildfire is India’s oldest and most prestigious rock band competition. With prizes worth\nlakhs of rupees and your prestige at stake, wildfire has been the launch pad for many\ncontemporary bands including - underground authority, parikrama, Kryptos, Zygnema,\nCassini’s division, and many more. So be ready to fulfill your love for rock at the wildfire\nfinals at Kharagpur! Wildfire is a western and eastern rock band competition, open to any\ncollege or semi-professional band from India and abroad.",
					min_participation: 2,
					max_participation: 12,
					rules: [
						"",
						"1. Offline prelims will be conducted in Bangalore, Delhi, Mumbai, Kolkata, Shillong\nand Jaipur.",
						"2. After the first round, a shortlist of bands would be released who will qualify to\nperform at the main event at IIT Kharagpur.",
						"3. The main event at IIT Kharagpur would consist of 2 rounds: prefinals and finals.",
						"4. In prefinals at IIT Kharagpur, a group will be required to perform at least three\nnumbers of their choice within 20 minutes. (Amps on to amps off and inclusive of\nsound check)",
						"5. In finals, a group will be required to perform at least 4 numbers of their choice\nwithin 40 minutes (Amps on to amps off inclusive of sound check).",
						"6. Bands will be disqualified on the spot for misconduct, obscenity or foul\nlanguage, and will be banned from performing at all subsequent editions of spring\nfest.",
						"7. Only English and Hindi Rock Music are allowed",
						"8. Equipment provided will be: a. One bass amplifier speaker b. One lead amplifier\nspeaker c. Adequate microphones d. Drum set (Participants can bring along with\nyour own cymbals and chokes/high hats).",
						"9. Bands will have to bring their own musical instruments and special effects.\nHowever, programmed music is not allowed.",
						"10. Spring Fest will not be held responsible for the failure of any instrument.",
						"11. Judging criteria includes:\n\n A. Musical Performance and Skill (40 points)\n\n B. Stage Presence and Showmanship (30 points)\n\n C. Originality and Creativity (30 points)\n\n The judges' collective scores across these categories will determine the final outcome of the competition.",
					],
					is_group: true,
					event_status: true,
					latitude: "22 N",
					longitude: "66 E",
					score: 1,
				},
				{
					id: 11,
					genre: "Music",
					name: "Sargam",
					tagline: "Eastern Fusion Band Competition",
					writeup:
						"This spring get ready to float with the melodies of indian classical and folk music with a twist\nof fusion. The eastern fusion group competition witnesses huge participation and gives a\nplatform to various maestros in the rising. Tune your instruments and strike the right notes to\nbeat some of the ustads of indian music and win prizes worth more than a lakh rupees.\nThe event is open to any eastern group and songs in hindi are permitted. The event will take\nplacein 1 round. There is no limit on the team size.",
					min_participation: 2,
					max_participation: 20,
					rules: [
						"",
						"1. A group can perform for a maximum of 20 minutes (Amps on to Amps off Inclusive of Sound Check) and has to perform at least 3 songs within the given time.",
						"2. Only keyboard part of synthesizer is allowed (Rhythm part is not allowed).",
						"3. Groups will have to bring their own instruments and special effects. However,\nprogrammed music is not allowed.",
						"4. Equipment provided will be: a. One bass amplifier speaker. b. One lead amplifier\nspeaker. c. Adequate microphones. d. 10000 Watts P.A. System",
						"5. Drum set (you can bring along with your own cymbals and chokes/high hats).",
						"6. Spring Fest team will not be held responsible for the failure of any instruments.",
						"7. Tuning facilities would be provided backstage. The decision of the judges will be\nfinal and binding.\n 8) Judging criteria includes:\n\n A. Musical Performance and Skill (40 points)\n\n B. Stage pPresence and Showmanship ( (30 points)\n\n C. Originality and Creativity (30 points)\n\n The judges' collective scores across these categories will determine the final outcome of the competition.",
					],
					is_group: true,
					event_status: true,
					latitude: "22 N",
					longitude: "66 E",
					score: 1,
				},
				{
					id: 10,
					genre: "Music",
					name: "Retrowave",
					tagline: "Solo Remix Competition",
					writeup:
						"With the best music-making community in rise and the level of production skillz\ncoming through the country; start working your magic!. This is an individual event and will take place in 1 round : online finals judging criteria: originality, quality of production, use of samples, use of tracks, mixing/mastering",
					min_participation: 1,
					max_participation: 1,
					rules: [
						"",
						"1. Participants need to submit their Digital Audio Workstation (DAW) file of the software used in music production. (For Example: If you are using FL Studio; send the .flp file)",
						"2. The participants need to submit the judging entries (tracks prepared) in any uncompressed audio format. (The audio file sent for judging shall be the same as the DAW file submitted).",
						"3. The original tracks selected shall not be remixes. Copying and stealing the remixes will lead to disqualification. If found using pre-looped tracks/pre-extended mixes/re-cued tracks/pre-pitched tracks will be disqualified.",
						"4. Participants will have to perform their composition during the main fest.",
						"5. The entry should be submitted to music.sf2025@gmail.com.",
						"6. Time limit is 4 minutes (music on to music off) exceeding which by 1 minute will lead to disqualification.",
						"7. Judging criteria includes:\n\n A. Creativity and Innovation (40 points)\n\n B. Musicality and Production (30 points)\n\n C. Genre Relevance (30 points)\n\n The judges' collective scores across these categories will determine the final outcome of the competition.",
					],
					is_group: false,
					event_status: true,
					latitude: "22 N",
					longitude: "66 E",
					score: 1,
				},
				{
					id: 6,
					genre: "Music",
					name: "Beat IT",
					tagline: "Beatboxing Competition",
					writeup:
						"Calling all aspiring beatboxers! Showcase your rhythmic prowess and original vocal beats in our exciting beatboxing competition and be recognized for your unique talent and creativity",
					min_participation: 1,
					max_participation: 1,
					rules: [
						"1. It is a solo competition.",
						"2. Time limit for the performance will be 2 minutes, exceeding which by 20s\n will lead to disqualification.",
						"3. This will be a 1vs1 battle rounds among the top 16 participants wherein each beatboxer would be given 2 minutes each and the winners will be decided by the judges.",
						"4. Top 16 participants will be decided by an initial showcase round where the judges will score all the participants based on the given criteria.",
						"5. The winner from each battle will be promoted to the next battle and the opponents will be decided by the judges in whichever way they seem fit.",
						"6. The decision of the judges will be final and binding.",
						"7. Use of musical instruments will lead to disqualification.",
						"8. In case judges are not able to decide, another 30 seconds will be provided to each participant to perform. It will be avoided whenever possible.",
						"4. Judging criteria includes:\n A. Technical skills (40 points)\n B. Creativity and originality (30 points)\n C. Performance and stage presence (30 points)",
					],
					is_group: false,
					event_status: true,
					latitude: "22 N",
					longitude: "66 E",
					score: 1,
				},
				{
					id: 7,
					genre: "Music",
					name: "Lakeside Dreams",
					tagline: "Acoustic Jamming",
					writeup:
						"Have you been into jamming recently? Be it solo or in groups, lake side dreams is the perfect platform to showcase your fervour in acoustic jamming. The competition invites some of the best musicians from across india to sing to the tunes of nature at the lake side stage. This competition is open to any acoustic jam based band and individual performer (without an accompanist) and will take place in 1 round. The winners will be separate for individuals and groups. Vocals are compulsory. The judging will be on the overall performance and not just on the instrumental performance.",
					min_participation: 1,
					max_participation: 15,
					rules: [
						"",
						"1. Only songs in English and/or Hindi are permissible.",
						"2. Solo and Group event will be conducted and judged separately.",
						"3. No other person is allowed to perform in Solo performance other than the participant.",
						"4. Only non-electrical musical instruments (guitars, flutes etc.) are allowed. However one synthesizer is allowed per entry. A bass guitar can be used without a processor.",
						"5. Patch change for synthesizers is not allowed in the middle of a song.",
						"6.The following equipments will be provided by us: Power supply for synthesizer, Microphones and sounds.",
					],
					is_group: true,
					event_status: true,
					latitude: "22 N",
					longitude: "66 E",
					score: 1,
				},
				{
					id: 12,
					genre: "Music",
					name: "SF Idol",
					tagline: "Solo Singing",
					writeup:
						"Calling all solo singing virtuosos! Showcase your vocal brilliance in an electrifying competition set\n amidst a vibrant atmosphere, where your melodious voice takes center stage. Embrace the spotlight,\n captivate hearts, and leave an indelible mark with your musical prowess at this prestigious event!",
					min_participation: 1,
					max_participation: 1,
					rules: [
						"",
						"1. Participants can perform any number of songs (in Hindi, English or both) within the time limit.",
						"2. Participants can perform with one instrumental accompaniment or with a backing track but the\n judging will be done solely on the basis of vocal performance.",
						"3. Performers can be disqualified on the spot for misconduct, obscenity or foul language.",
						"4. The time limit for each user is 5 minutes",
						"5.  Mail the backing track at music.sf2025@gmail.com with the subject “SF Idol:\n <Participant Name>, <SFID>”.",
					],
					is_group: false,
					event_status: true,
					latitude: "22 N",
					longitude: "66 E",
					score: 1,
				},
			],
		},
		{
			genre: "Dramatics",
			events: [
				{
					id: 14,
					genre: "Dramatics",
					name: "I Me Myself",
					tagline: "Mono-Acting Competition",
					writeup:
						"Step into the spotlight and embody characters that resonate. Elevate your solo performance at our mono-acting competition, where your portrayal's depth and emotions take center stage.",
					min_participation: 1,
					max_participation: 1,
					rules: [
						"1. This is an individual event where participants have to present a mono act on any theme.",
						"2. 1 person is allowed to assist with sounds and 2 people for the lights at max.",
						"3. Language of the act can be English or Hindi.",
						"4. Total time allotted for every performance is 4 minutes (empty stage to empty stage)",
						"5. Exceeding the time limit by 1 minute will lead to disqualification.",
						"6. Participants can bring their own music for the act in a pen drive but recorded vocals are not allowed.",
						"7. No naked flames or live animals are allowed on stage.",
						"8. Any instance of vulgarity or disturbing content of any order will lead to forceful halt of performance and immediate disqualification.",
						"9. Judging criteria includes:\n A. Character potrayal (40 points)\n B. Delivery and expression (30 points)\n C. Interpretation and creativity (30 points)\n The judges' collective scores across these categories will determine the final outcome of the competition.",
					],
					is_group: false,
					event_status: true,
					latitude: "22 N",
					longitude: "66 E",
					score: 1,
				},
				{
					id: 15,
					genre: "Dramatics",
					name: "Dumbstruck",
					tagline: "Silent Act",
					writeup:
						"Sometimes silence says what words can't. Spring fest presents you an opportunity to\nshowcase your talent of expressions, gesticulations and body movements without use of\nspeech so bring out your excellent dramatic and creative side and amaze the audience.",
					min_participation: 1,
					max_participation: 1,
					rules: [
						"",
						"1. Performance should be a non-verbal act.",
						"2. Time limit is 4 minutes.",
						"3. This is an individual event and will take place in 1 round.",
						"4. No recorded music, recorded sounds, musical instruments, recognizable words, indicative makeup, indicative costumes or props are allowed.",
						"5. Video Editing is not allowed.",
						"6. Judging criteria includes:\n\n A. Artistic Expression and Creativity (40 points)\n\n B. Technical Skills and Execution (30 points)\n\n C. Stage Utilisation and Impact (30 points)\n\n The judges' collective scores across these categories will determine the final outcome of the competition.",
					],
					is_group: false,
					event_status: true,
					latitude: "22 N",
					longitude: "66 E",
					score: 1,
				},
				{
					id: 17,
					genre: "Dramatics",
					name: "Rangmanch",
					tagline: "Stage Play",
					writeup:
						"If you think you can mesmerize the audience with acting, script, dialogues and sets - then Rangmanch is\nyour call! It cannot get better than the annual stage play competition at Spring Fest. Once the stage is set\nand all is ready - it is show time!",
					min_participation: 5,
					max_participation: 35,
					rules: [
						"",
						"1. This is a group event. Each team should have a minimum of 5 actors. In\naddition, there can be one person in charge of music and a maximum of 3 people\nfor lights.",
						"2. The event will take place in 2 rounds, pre-finals and finals. Total time allotted for\neach team in the prelims is 15 minutes and for the finals is 50 minutes.",
						"3. Language of the play can be English/Hindi. Mime is allowed.",
						"4. Stage Area: 20ft x 36ft (approx.)",
						"5. Pre-registration before 19th January is mandatory. Teams should mail a soft\ncopy of the script to dramatics.sf2025@gmail.com.",
						"6. This is an inter-collegiate event and there shall be only 1 team per college. The\nteams should carry an official letter from their respective institutes signed by a\ncompetent authority, mentioning the names of the participants.",
						"7. Once a team registers, their preference for a slot for prelims and lights practice\nwill be taken by email. The organizing team shall try to give the preferential slot as\nlong as it is available. The decision made by the organizing team will be final and\nbinding.",
						"8. The teams will be informed regarding their lights practice and prelims slots by\nemail.",
						"9. The time duration for prelims and finals includes performance time and stage\nsetting time. The given time duration is from the empty stage to the empty stage.",
						"10. In the finals, if a team exceeds 50 minutes, 15% of the total works obtained\nwill be deducted. If a team exceeds 55 min, it stands to be debarred from the\nevent.",
						"11. Judging Criterion:\n\n a. Acting and Storytelling Skills (40 points)\n\n b. Script and Overall Impact (40 points)\n\n c. Production Values (20 points)",
						"12. Microphones and backstage mikes for narration, lights, and a laptop to play\nsounds will be provided.",
						"13. Recorded vocals are not allowed, only instrumental music is allowed.",
						"14. The teams are expected to bring their own music on CD or pen drive for the\nplay.",
						"15. In case of malfunctioning of any equipment provided, the team will be allowed\nto repeat their performance from the last scene change or from the point of\ndisruption that the team wishes. It depends on the judge’s discretion as to how\nmuch grace time will be given to the performing team.",
						"16. All costumes and accessories are to be arranged by the participating team. The\norganizing committee is responsible for the infrastructural facilities only and shall\nnot be responsible for the security of items left behind in green rooms or on stage\nafter the performance.",
						"17. Requests for special effects and props should be communicated at least a\nweek in advance by both emails and over the telephone. The same will be provided\nonly if possible.",
						"18. No naked flames or live animals are allowed on stage.",
						"19. Any instance of vulgarity or disturbing content of any order will lead to a forceful halt of performance and immediate disqualification.",
					],
					is_group: true,
					event_status: true,
					latitude: "22 N",
					longitude: "66 E",
					score: 1,
				},
				{
					id: 16,
					genre: "Dramatics",
					name: "Nukkad",
					tagline: "Street Play",
					writeup:
						"Exploiting the power of a street gathering, nukkad or street plays have been\nthe medium of the voice of the people from time immemorial. Unleash your\ncreativity on the pavement stage! Join our street play competition, where\nyour voice becomes a powerful instrument for social change, blending art\nand activism in the most impactful way.",
					min_participation: 6,
					max_participation: 27,
					rules: [
						"1. Teams are expected to perform at an open-air venue, on a stage with an audience on all sides.",
						"2. The permitted team limit is 6-25 participants excluding 2 instrumentalists.(optional)",
						"3. Time limit shall be 15 minutes, exceeding which by 3 minutes will lead to disqualification.",
						"4. .The play should be in Hindi/ English.",
						"5. Usage of fire, water or smoke is not allowed. Any props, if used, must be cleared off by the participants after the performance within the time limit.",
						"6. Any instance of vulgarity or disturbing content of any order will lead to forceful halt of performance and immediate disqualification.",
						"7.Only live music is allowed. Teams will have to bring their own instruments.",
						"8. Gulaal or any props, if used, must be cleared off by the participants after their performance within the performance time allotted to them.",
						"9. Judging criteria includes:\n A. Content, theme and message (40 points)\n B. Performance , Direction, gimmicks (40points)\n C. Interaction and improvisation (20 points)",
					],
					is_group: true,
					event_status: true,
					latitude: "22 N",
					longitude: "66 E",
					score: 1,
				},
			],
		},
		{
			genre: "Literary",
			events: [
				{
					id: 27,
					genre: "Literary",
					name: "Poetry Slam",
					tagline: "Poetry Recital Competition",
					writeup:
						"Unleash your words and emotions on our poetic stage. Join the poetry competition to weave your verses into a tapestry of expression, where each syllable carries the power to captivate and resonate.",
					min_participation: 1,
					max_participation: 1,
					rules: [
						"",
						"1. Poems can be on any subject and in any style but must be original and in Hindi or English only.",
						"2. Use of props, special costumes, musical instruments or pre-recorded music is not allowed.",
						"3. Poems once performed may not be repeated in further rounds, except in case of tie-breaking rounds, violation of which disqualifies the poet.",
						"4. Time limit is three minutes, exceeding which by 30 seconds will lead to disqualification.",
						"5. Participant may not repeat primary authorship in a bout. Every poet who performs during a bout must be a primary author.",
						"6. Judging criteria includes:\n\n A. Content and theme (40 points)\n\n B. Language and delivery (30 points)\n\n C. Emotion and connection (30 points)\n\n The judges' collective scores across these categories will determine the final outcome of the competition.",
						"7. Winners get a chance to grab a direct spot in Poetry slam (Hindi and english respectively) during the main fest.",
					],
					is_group: false,
					event_status: false,
					latitude: "22 N",
					longitude: "66 E",
					score: 1,
				},
				{
					id: 20,
					genre: "Literary",
					name: "Poetry Slam",
					tagline: "POETRY RECITAL COMPETITION",
					writeup:
						"Bring your eloquence to life, captivating hearts with the power of your words and the depth of your expression. Join us for an evocative evening, where each recital becomes a window to the soul,leaving an indelible mark through the artistry of spoken word!.",
					min_participation: 1,
					max_participation: 1,
					rules: [
						"",
						"1. Poems can be on any subject and in any style but must be original and in Hindi\nor English only.",
						"2. The competition will be conducted separately for Hindi and English poetry.",
						"3. Use of props, special costumes, musical instruments or pre-recorded music is not allowed.",
						"4. Poems once performed may not be repeated in further rounds, except in case of\ntie-breaking rounds, violation of which disqualifies the poet.",
						"5. Participants may not repeat primary authorship in a bout. Every poet who performs during a bout must be a primary author.",
						"6. POEM SUBMISSION DEADLINE: 19th January, 2025",
						"7. SUBMISSION FORMAT: Mail the poem at literary.sf2025@gmail.com with the subject “Poetry Slam :<Participant Name>, <SFID>”.\n\nJudging Criteria: \n\nContent and Theme (40 points)\n\nLanguage and Delivery (30 points)\n\nEmotion and Connection (30 points)",
					],
					is_group: false,
					event_status: true,
					latitude: "22 N",
					longitude: "66 E",
					score: 1,
				},
				{
					id: 23,
					genre: "Literary",
					name: "India Calling",
					tagline: "Case Study Competition",
					writeup:
						"Spring Fest presents India Calling, a case study presentation based on a social problem statement. An\nevent for the students and faculty alike as young minds present their ideas that have both financial and\nsocial goals integrated to its purpose! Participants need to be socially motivated and practical into their\napproach.",
					min_participation: 2,
					max_participation: 5,
					rules: [
						"",
						"1. The competition will be listed on unstop (dare2compete) platform.",
						"2. The problem statement will be released one month before the fest on the platform.",
						"3. The presentation should have a maximum of 30 pictures accompanied by captions and slogans, as well as a 500-word policy proposal.",
						"4. The final round would be campus round, for the campus round, the teams need to give a 20-minute presentation.",
						"5.The participants are free to decide the way of presentation of their report.",
						"6. A hard copy of the report must be submitted to the organizing team at the time of the presentation. \n\nJUDING CRITERIA:",
						"6. For the finals, the teams need to give a 20-minute presentation.\n\nContent (40 points)\n\nProjection of Theme and Presentation (40 points)\n\nPolicy Proposal (20 points)",
					],
					is_group: true,
					event_status: true,
					latitude: "22 N",
					longitude: "66 E",
					score: 1,
				},
				{
					id: 21,
					genre: "Literary",
					name: "Hindi Poetry Slam",
					tagline: "Hindi Poetry Recital",
					writeup:
						"One of the events of the fest, which involves the combined art of story-telling, stand-up and\npoetry writing, poetry slam happens to be the flagship event of literary genre. The event\nattracts poetry enthusiasts from all over the country to enchant the audience and fill their\nartistic hunger. The event serves instrumental in recognizing the new generation poets in\nIndia.",
					min_participation: 1,
					max_participation: 1,
					rules: [
						"",
						"1. Poems can be on any subject and in any style but must be original and in Hindi\nor English only.",
						"2. Use of props, special costumes, musical instruments or pre-recorded music is\nnot allowed.",
						"3. There is no upper limit of participants from a particular college. The judging shall\nhowever be done individually.",
						"4. Poems once performed may not be repeated in further rounds, except in case of\ntie-breaking rounds, violation of which disqualifies the poet. Therefore, each poet\nshould plan on bringing at least 3 original poems to compete, with an extra poem\nas buffer for a tie.",
						"5. Time limit is three minutes. After three minutes, there is a 10-second grace\nperiod after which a penalty of",
						"0.5 is automatically deducted, without warning,\nfrom each poet's overall score for every subsequent 10 seconds.",
						"6. Teams may not repeat primary authorship in about. Every poet who performs\nduring a bout must be a primary author.",
						"7. The judges’ will give each poem a score from 0 to",
						"10.",
						"8. The sum of all the scores by all the judges in the panel for a particular round and\nthe grand total of each bout will be considered for their qualification to next bout.",
						"9. The best 3 poets shall be adjudged the winners of Poetry Slam.",
					],
					is_group: false,
					event_status: false,
					latitude: "22 N",
					longitude: "66 E",
					score: 1,
				},
				{
					id: 24,
					genre: "Literary",
					name: "Jumble The Good Word",
					tagline: "Word Game",
					writeup:
						"Challenge your lexicon prowess, strategic thinking, and quick wit in a battle of vocabulary and intellect. Engage in cerebral duels, unravel puzzles, and showcase your linguistic flair in an exhilarating competition that celebrates the power and depth of language!",
					min_participation: 1,
					max_participation: 2,
					rules: [
						"",
						"1. .Participants will be given random word game on the spot by the judges.",
						"2. The competition will take place in several rounds till the winners are decided.",
					],
					is_group: true,
					event_status: true,
					latitude: "22 N",
					longitude: "66 E",
					score: 1,
				},
				{
					id: 28,
					genre: "Literary",
					name: "Tell a Tale",
					tagline: "Story Recital Competition",
					writeup:
						"Craft enchanting narratives, ignite imagination, and transport the audience to realms of wonder with your storytelling finesse. Join us for an enchanting journey where every tale you weave becomes a mesmerizing experience, leaving a lasting impression on hearts and minds!",
					min_participation: 1,
					max_participation: 1,
					rules: [
						"",
						"1. Stories can be on any subject and in any style but must be original and in Hindi or English only.",
						"2.Use of props, special costumes, musical instruments or pre-recorded music is not allowed.",
						"3.Stories must be original creations by the participant. \n\nJudging Criteria: \n\nContent and Theme (40 points)\n\nLanguage and Connection (30 points)\n\nEmotion and Connection (30 points)",
					],
					is_group: false,
					event_status: true,
					latitude: "22 N",
					longitude: "66 E",
					score: 1,
				},
				{
					id: 25,
					genre: "Literary",
					name: "Just A Minute",
					tagline: "JAM",
					writeup:
						"An event for the grammar nazis and those glib of tongue, where you have to speak fluent and grammatically correct english for one minute without any hesitation, repetition or deviation.",
					min_participation: 1,
					max_participation: 1,
					rules: [
						"",
						"1. This is an individual event.",
						"2. Participants come on stage in random groups of 8 and will play multiple rounds of Just a Minute.",
						"3. In each round, the participants will be given a topic on which one of the 8 participants on stage will have to start speaking on the spot.",
						"4. He continues speaking until someone else from the group challenges him by 'jamming' him.",
						"5. If the challenge is successful, the person who jams, starts speaking in turn. This process continues till 1 minute is over.",
						"6. At the end of a minute, the next round will start with another topic.",
						"7. At the end of all the rounds, the participants with the maximum points in the group will move on to the next level.",
						"8. Points will be allotted as follows: 1 point for every second the participant speaks, in case of a challenge made by any participant on the grounds of hesitation, repetition or deviation, 5 points will be added to his score if he is correct and 5 points will be deducted if he is incorrect. In case of any other challenge as determined by the JAM master, 2 points will be added or subtracted, 5 points will be added to the score of the participant who is speaking at the end of the minute.",
					],
					is_group: false,
					event_status: false,
					latitude: "22 N",
					longitude: "66 E",
					score: 1,
				},
				{
					id: 18,
					genre: "Literary",
					name: "A Mighty Pen",
					tagline: "Journalism Competition",
					writeup:
						"Uncover compelling narratives, present well-researched articles, and showcase your knack for storytelling. Join us for an immersive experience where your journalistic skills shine, capturing the essence of current affairs and societal issues, leaving an indelible mark through the art of factual storytelling!",
					min_participation: 1,
					max_participation: 3,
					rules: [
						"",
						"1. The competition will be listed on unstop (dare2compete) platform",
						"2. The problem statement will be released on the platform one month before the fest.",
						"3. The final round would be a campus round, for campus round, teams have to prepare a report of up to 1500 words on the given topic, containing adequate pictures and data to support it.",
						"4. The teams are free to decide their way of presentation of the report.",
						"5. SUBMISSION DEADLINE: 19th January, 2025",
						"6. SUBMISSION FORMAT: Submit your entry at unstop with the title “A Mighty Pen: <Team Name>,<College Name>”.",
						"7. Judging Criteria: \n\nReport Content (40 points)\n\nInteractivity with Reader (30 points)\n\nPresentation (30 points)",
					],
					is_group: true,
					event_status: true,
					latitude: "22 N",
					longitude: "66 E",
					score: 1,
				},
				{
					id: 19,
					genre: "Literary",
					name: "Dumb C",
					tagline: "Dumb Charades Competition",
					writeup:
						"Bring your wit, acting skills, and quick thinking to the forefront as you communicate without words.Join us for a hilarious and exhilarating game night where laughter echoes, friendships strengthen, and your pantomime skills steal the spotlight!",
					min_participation: 3,
					max_participation: 3,
					rules: [
						"",
						"1. The event will take place in two rounds, Prelims and Finals.",
						"2. In the prelims, there will be 25 questions on Movies/Literature/Personality/Advertisements flashed on the screen.",
						"3. The top 8 teams will qualify for the finals which will be three rounds of Dumb Charades.",
						"4. In the finals, in each round, one person from the team will act out the clue and the others will guess.",
						"5. The 1st round will be based on Movies.",
						"6. 2nd round will be based on Movie Personalities.",
						"7. A maximum of 45 seconds will be given to the teams to guess the correct movie name and personality.",
						"8. For the 3rd round, enacting the film itself instead of the Dialogues/Songs not allowed.",
						"9. For the 3rd round, enacting the film itself instead of the Dialogues/Songs not allowed.",
						"10. A maximum of 60 seconds will be given to the teams to guess the correct Dialogues/Songs.",
						"11. In each of the 3 rounds, every team shall be given 3 clues to enact and each person should be an enactor at least once in all rounds combined.",
						"12. There will be total 4 guesses to be allowed per clue for each round.",
						"13. If the team fails to guess the correct answer in the stipulated time, 10 seconds will be added to the team's time in addition to the allocated time for that clue.",
						"14. The team with the minimum time at the end of three rounds wins.",
					],
					is_group: true,
					event_status: true,
					latitude: "22 N",
					longitude: "66 E",
					score: 1,
				},
				{
					id: 22,
					genre: "Literary",
					name: "Impromptu",
					tagline: "ELOCUTION COMPETITION",
					writeup:
						"Embrace the challenge of articulating thoughts fluently and persuasively on unprepared topics. Step into the spotlight, seize the moment, and captivate the audience with your impromptu speaking skills.",
					min_participation: 1,
					max_participation: 1,
					rules: [
						"",
						"1. In the finals, the order of finalists will be decided by the draw of lots.",
						"2. Each participant will be given a social (Picture or Video) topic. He has to speak\non either for or against the topic.",
						"3. Each participant will be given 30 seconds to think and 90 seconds to speak.",
						"4. Whenever the judge blows a whistle/ring a bell/give any form of sign, the speaker will have to contradict his/her views. The sign may be given more than once for a contestant or may not be given at all.",
						"5. If the participant wishes to change the topic he may do so only one time after a penalty of 10% of the total marks.",
						"6. If the participants don't speak for one minute, they will be disqualified.",
						"7. Exceeding the time limit for more than 30 seconds will lead to disqualification.",
						"8.Judging Criteria: \n\nClarity of Thought and Structure (40 points)\n\nSpontaneity and Adaptability (30 points)\n\nDeliveery and Engagement (30 points)",
					],
					is_group: false,
					event_status: true,
					latitude: "22 N",
					longitude: "66 E",
					score: 1,
				},
				{
					id: 26,
					genre: "Literary",
					name: "National Level Debate",
					tagline: "Debate Competition",
					writeup:
						"Delve into thought-provoking topics, present compelling arguments, and sharpen your rhetoric skills in a stimulating environment. Join us for a clash of ideas and ideologies, where articulate discourse and logical reasoning reign supreme, shaping perspectives and fostering intellectual growth!",
					min_participation: 1,
					max_participation: 1,
					rules: [
						"",
						"1. The event will take place in 2 rounds, prelims and finals.",
						"2. Both rounds will be presidential-style debates.",
						"3. Top 12 participants based on their points will go through to the final round.",
						"4. The total time allotted per debate is",
						"10.5 minutes. The time division is as follows:\n\n a. Speaker 1-2 minutes\n\n b. Speaker 2-4 minutes\n\n c. Speaker 1-2 minutes\n\n d. Direct question- 1 minute, maximum 2 questions\n\n e. Concluding statements- 15 seconds each.",
						"5. There will be a coin toss to decide the order of questioning and closing arguments. The winner gets to choose whether to take the first or second question or give the first or second closing statement.",
						"6. The participants will not be allowed to read out from any material but will be allowed to carry plain papers to jot down any points if required.",
						"7. The decision of the adjudicator is final.",
						"8.JUDING CRITERIA: \n\nContent of Speech (40 points)\n\nExpression (30 points)\n\nRebuttle Round (30 points)",
					],
					is_group: false,
					event_status: true,
					latitude: "22 N",
					longitude: "66 E",
					score: 1,
				},
			],
		},
		{
			genre: "Film Fest",
			events: [
				{
					id: 55,
					genre: "Film Fest",
					name: "Motion Tales",
					tagline: "REEL MAKING COMPETITION",
					writeup:
						"Craft a dynamic and captivating short video reel that encapsulates the energy, excitement, and diversity of Spring Fest. Embrace the opportunity to blend creativity, innovation, and the essence of our event into a mesmerizing reel that resonates with audiences, capturing the spirit of Spring Fest in a breathtaking visual narrative.",
					min_participation: 1,
					max_participation: 3,
					rules: [
						"",
						"1. The clips may be taken with any device.",
						"2. The participants will have to upload their reels online within the given deadline.",
						"3. Obscenity of any kind is not allowed and shall lead to disqualification. Photo animations, slide shows, remixes, spoofs and advertisements must be avoided.",
						"4. The decision of the judges and the organizing team will be final and binding.",
						"5. Spring Fest reserves the right to use the video entries on social media (suitable credits will be given to the people responsible for the creation of the content)",
						"6. Judging criteria includes:\n\n A. Engagement and Impact (40 points)\n\n B. Technical Quality and Production (30 points)\n\n C. Creativity and Originality (30 points)\n\n The judges' collective scores across these categories will determine the final outcome of the competition.",
						"7. Winners will be declared on the day of the event.",
					],
					is_group: true,
					event_status: true,
					latitude: "22 N",
					longitude: "66 E",
					score: 1,
				},
				{
					id: 29,
					genre: "Film Fest",
					name: "A Picture Tale",
					tagline: "PHOTO STORY COMPETITION",
					writeup:
						"Let your images narrate tales in our captivating photo story competition! Embrace the power of photography to tell compelling stories, evoke emotions, and capture moments that resonate. Each image forms a part of a larger narrative, showcasing your ability to communicate stories through a series of captivating photographs.",
					min_participation: 1,
					max_participation: 1,
					rules: [
						"",
						"1. This is an individual competition.",
						"2. Any camera may be used (Digital SLRs, Mobile Camera etc.)",
						"3. Each participant will have to submit a maximum of 10 photographs clicked during a specified time.",
						"4. The photographs shall also be submitted as a PDF file along with a suitable title and a brief photo story description of not more than 30 words.",
						"5.  The theme for the event shall be released one month before the fest on Unstop.",
						"6. Photographs must be clicked after the theme is officially released. The EXIF data shall be checked and plagiarism will be dealt severely.",
						"7. Only basic photo editing is allowed i.e. cropping, adjusting the hue/saturation, brightness, contrast levels. Photo morphing is strictly not allowed.",
						"8. Spring Fest will not be responsible for any technical errors due to non- compatibility of photos",
						"9. Judging criteria includes:\n\n A. Composition and Story Depiction (40 points)\n\n B. Relevance to Theme (30 points)\n\n C. Overall Impact and Creativity (30 points))\n\n The judges' collective scores across these categories will determine the final outcome of the competition.",
						"10. Winners will be declared on the day of the event.",
					],
					is_group: false,
					event_status: true,
					latitude: "22 N",
					longitude: "66 E",
					score: 1,
				},
				{
					id: 31,
					genre: "Film Fest",
					name: "SFM",
					tagline: "Short Film Making Competition",
					writeup:
						"Do you consider yourself a visionary or an amateur director? Then Short Film Making competition at Spring Fest is your chance to prove your worth by producing a short film of your own and displaying it on a large screen before a large audience to enjoy and appreciate your brilliance. The short film has to be made on a certain theme that would be released two months before the final event.",
					min_participation: 2,
					max_participation: 20,
					rules: [
						"",
						"1. The team size can be 10 to 20 people including actors.",
						"2. The time range for the short film will be 6 to 8 min.",
						"3. The movie should either be in Hindi or English or both. No other languages are permitted.",
						"4. The video may be taken with any device.",
						"5. A list of specific situations will be released on the website one month before the fest. At least one of these situations has to be included in the short film.",
						"6. It is imperative that at least one of the actors in the short film registers at the control tent to confirm the authenticity of the short film. The participating actor has to submit his/her SF ID as well, when submitting the video, along with scanned college ID’s, photos and SF ID’s of all the group members.",
						"7. The participants will have to submit their films online at filmfest.sf2025@gmail.com by 20th of January. It can have either an attached file or link to the movie. The mail should have the subject “SF-Short Film Making-Group Name”",
						"8. Spring Fest shall not be responsible for any issues arising due to non-compatibility.",
						"9. Obscenity of any kind is not allowed and shall lead to disqualification. Photo animations, slide shows, remixes, spoofs and advertisements must be avoided.",
						"10. The decision of the judges and the organizing team will be final and binding.",
						"11. Spring Fest reserves the right to use the video entries on social media (suitable credits will be given to the people responsible for the creation of the content).",
						"12. The use of copyright content like background music, etc. is not allowed and will lead to disqualification.",
						"13. Judging criteria includes:\n\n A. Story and Screenplay (40 points)\n\n B. Editing and Production (30 points)\n\n C. Acting and Impact (30 points)\n\n The judges' collective scores across these categories will determine the final outcome of the competition.",
						"14. Winners will be declared on the day of the event.",
					],
					is_group: true,
					event_status: true,
					latitude: "22 N",
					longitude: "66 E",
					score: 1,
				},
				{
					id: 30,
					genre: "Film Fest",
					name: "Lights Camera SF",
					tagline: "Documentary making event",
					writeup:
						"This is your chance to make a short film covering one of the biggest social and cultural fests of\nIndia! So, all of spring fest is a game and may the most creative and omniscient team win!",
					min_participation: 1,
					max_participation: 20,
					rules: [
						"",
						"1.It is a documentary making event.",
						"2.Team size should be 20 or less.",
						"3. The teams will have to come to Kharagpur and shoot a documentary starting\nfrom the 1st day of Spring Fest 2025, encompassing the fest.",
						"4.The documentary should be under 8 minutes.",
						"5. The participants will have to submit their videos online at\nfilmfest.sf2025@gmail.com by 4th of February. It can have either an attached file\nor link to the movie. The mail should have the subject “SF Lights Camera SF-\nGroup Name”. Spring Fest is not responsible for any technical problems arising out\nof non-compatibility of the videos.",
						"6. The complete movie has to be submitted in .mpeg or .avi formats only. Spring\nFest shall not be responsible for any issues arising due to non-compatibility.",
						"7.  The documentary should be under 8 minutes.",
						"8. Spring Fest reserves the right to use the video entries on social media (suitable\ncredits will be given to the people responsible for the creation of the content).",
						"9. Spring Fest is not responsible for any technical problems arising out of non-compatibility of the videos.",
						"10. The use of copyright content like background music, etc. is not allowed and will lead to disqualification",
						"11. Judging criteria includes:\n\n A. Fest Coverage and Screenplay (40 points)\n\n B. Technical Quality and Production (30 points)\n\n C. Creativity and Originality (30 points)\n\n The judges' collective scores across these categories will determine the final outcome of the competition.",
					],
					is_group: true,
					event_status: true,
					latitude: "22 N",
					longitude: "66 E",
					score: 1,
				},
			],
		},
		{
			genre: "Quiz",
			events: [
				{
					id: 33,
					genre: "Quiz",
					name: "Mary Bucknel Trophy(MBT)",
					tagline: "General Quiz",
					writeup:
						"The Mary Bucknell trophy is one of the oldest and the most coveted quizzing competition in the east. The general quiz has been a part of spring fest, since the early 70’s. A yearning for knowledge and a passion for quizzing along with general awareness is all that is required.\n",
					min_participation: 1,
					max_participation: 4,
					rules: [
						"",
						"1.This is a team event. Each team will have a maximum of four members.",
						"2.The event will take place in two rounds, written prelims followed by finals.",
						"3.8 teams from the prelims will qualify for the finals.",
						"4.In the finals, the quiz master will explain the detailed rules before conducting every round.",
						"5.The quiz master’s decision is final and binding.",
						"6.The organizing team reserves the right to change or modify any of the rules",
					],
					is_group: true,
					event_status: true,
					latitude: "22 N",
					longitude: "66 E",
					score: 1,
				},
				{
					id: 34,
					genre: "Quiz",
					name: "SpEnt",
					tagline: "Sports and Entertainment Quiz",
					writeup:
						"From page 3 to cricket and kabaddi, this quiz covers it all. The sports and entertainment quiz is tailor made to test your awareness about the glamour world from actors to movies and the sporting world from great sports persons to their statistics and records. Conducted in a unique fashion, there is something in it for every member of the audience.",
					min_participation: 1,
					max_participation: 4,
					rules: [
						"",
						"1.This is a team event. Each team will have a maximum of four members.",
						"2.The event will take place in two rounds, written prelims followed by finals.",
						"3.8 teams from the prelims will qualify for the finals.",
						"4.In the finals, the quiz master will explain the detailed rules before conducting every round.",
						"5.The quiz master’s decision is final and binding.",
						"6.The organizing team reserves the right to change or modify any of the rules",
					],
					is_group: true,
					event_status: true,
					latitude: "22 N",
					longitude: "66 E",
					score: 1,
				},
				{
					id: 32,
					genre: "Quiz",
					name: "BizTech",
					tagline: "Business and Tech Quiz",
					writeup:
						"Time has come to capitalize on the well preserved and reserved acumen for business matters and technical bits. From logos to taglines of the companies to historic people and events in the it industry, nothing is left behind. This is the apt quiz for you if you live on a daily dose of ‘the economic times’ and ‘digit’.\n",
					min_participation: 1,
					max_participation: 4,
					rules: [
						"",
						"1.This is a team event. Each team will have a maximum of four members.",
						"2.The event will take place in two rounds, written prelims followed by finals.",
						"3.8 teams from the prelims will qualify for the finals.",
						"4.In the finals, the quiz master will explain the detailed rules before conducting every round.",
						"5.The quiz master’s decision is final and binding.",
						"6.The organizing team reserves the right to change or modify any of the rules",
					],
					is_group: true,
					event_status: true,
					latitude: "22 N",
					longitude: "66 E",
					score: 1,
				},
				{
					id: 56,
					genre: "Quiz",
					name: "Cinemania",
					tagline: "Movies Quiz",
					writeup:
						"Test your cinematic knowledge and love for movies in our exciting movies quiz! Dive into a fun-filled challenge featuring trivia, iconic scenes, and memorable quotes from your favorite films. Showcase your passion for cinema, compete with fellow movie buffs, and prove your expertise in the world of motion pictures.",
					min_participation: 1,
					max_participation: 4,
					rules: [
						"",
						"1.This is a team event. Each team will have a maximum of four members.",
						"2.The event will take place in two rounds, written prelims followed by finals.",
						"3.8 teams from the prelims will qualify for the finals.",
						"4.In the finals, the quiz master will explain the detailed rules before conducting every round.",
						"5.The quiz master’s decision is final and binding.",
						"6.The organizing team reserves the right to change or modify any of the rules",
					],
					is_group: true,
					event_status: true,
					latitude: "22 N",
					longitude: "66 E",
					score: 1,
				},
				{
					id: 57,
					genre: "Quiz",
					name: "Otakon Quest",
					tagline: "Anime Quiz",
					writeup:
						"Test your anime knowledge and love for the world of Japanese animation in our exciting Anime Quiz! Dive into a fun-filled challenge featuring trivia, iconic scenes, and memorable quotes from your favorite anime series and films. Showcase your passion for anime, compete with fellow otakus, and prove your expertise in the vibrant world of anime.",
					min_participation: 1,
					max_participation: 4,
					rules: [
						"",
						"1.This is a team event. Each team will have a maximum of four members.",
						"2.The event will take place in two rounds, written prelims followed by finals.",
						"3.8 teams from the prelims will qualify for the finals.",
						"4.In the finals, the quiz master will explain the detailed rules before conducting every round.",
						"5.The quiz master’s decision is final and binding.",
						"6.The organizing team reserves the right to change or modify any of the rules",
					],
					is_group: true,
					event_status: true,
					latitude: "22 N",
					longitude: "66 E",
					score: 1,
				},
			],
		},
		{
			genre: "Fine Arts",
			events: [
				{
					id: 58,
					genre: "Fine Arts",
					name: "Frenzy Fabric",
					tagline: "T - SHIRT DESIGN COMPETITION",
					writeup:
						"The Frenzy Fabric (T-Shirt Design Competition) is here to give you a canvas to unleash your imagination! This competition provides the perfect opportunity to translate your vision into a wearable masterpiece. Let your design inspire, stand out, and leave an impact.",
					min_participation: 1,
					max_participation: 1,
					rules: [
						"",
						"1. This is an individual event. Registrations will be accepted on the spot.",
						"2. The event will be conducted in one round.",
						"3. Participants are needed to make a craft work out of the given logistics at the time of the event.",
						"4. Designs should be original and created using graphic design software (e.g., Adobe Illustrator,Photoshop, Canva, etc.) or hand-drawn (must be scanned in high-resolution).",
						"5. Submitted designs must include a brief description (50-100 words) explaining the concept and idea behind the design.",
						"6. Files must be submitted in [PDF/JPEG/PNG] format with high resolution (minimum 300 dpi).",
						"7. Use of any copyrighted or plagiarized material will lead to immediate disqualification.\n\nJUDING CRITERIA:\n\nArtistic Creativity and Originality (40 points)\n\nTechnical Skill and Execution (30 points)\n\nOverall Presentation (30 points)",
					],
					is_group: false,
					event_status: true,
					latitude: "22 N",
					longitude: "66 E",
					score: 1,
				},
				{
					id: 59,
					genre: "Fine Arts",
					name: "Strokes on Streets",
					tagline: " ROAD PAINTING COMPETITION",
					writeup:
						"The Strokes on Streets (Road Painting Competition) invites participants to create impactful and eyecatching artworks directly on open pathways, turning them into masterpieces for all to admire. Let the streets speak through your strokes and leave a colorful legacy.",
					min_participation: 1,
					max_participation: 1,
					rules: [
						"",
						"1. This is an individual event. Registrations will be accepted on the spot.",
						"2. The event will be conducted in one round.",
						"3. Participants must create road artwork based on the given theme within a designated area.",
						"4. All art supplies (paints, brushes, and tools) should be carried by the Participants. Use of personal supplies is permitted with prior approval.",
						"5. Paints used must be non-toxic and washable, ensuring no environmental harm.",
						"6. The allotted time for painting is 3 Hours.",
						"7. Designs must be original, creative, and non-offensive in nature. Plagiarized or inappropriate work will be disqualified.\n\nJUDGING CRITERIA:\n\nCreativity and originality (25 points)\n\nRelevance to the theme (20 points)\n\nVisual impact and overall composition (30 points)\n\nTeamwork and time management (25 points)",
					],
					is_group: false,
					event_status: true,
					latitude: "22 N",
					longitude: "66 E",
					score: 1,
				},
				{
					id: 42,
					genre: "Fine Arts",
					name: "Sketch It",
					tagline: "Pencil Sketching Competition",
					writeup:
						"Pick up your pencils, unleash your creativity, and let your imagination come alive on paper. Display your talent, capture emotions, and let your sketches tell powerful stories. Join a spirited sketching challenge,where every stroke showcases your artistic skill and vision.",
					min_participation: 1,
					max_participation: 1,
					rules: [
						"",
						"1. This is an individual event. Registrations will be accepted on the spot.",
						"2. The event will be conducted in one round.",
						"3. Participants are needed to make a painting based on a theme given to them on the spot within the time limit.",
						"4. Basic necessary logistics have to be carried by the participants themselves. Additional logistics will be provided at the venue.",
						"5. Use of any outside aids and the internet is strictly prohibited and may lead to disqualification.\n\nJudging Criteria: \n\nProportion and Perspective (35 points)\n\nComposition and Components (35 points)\n\nShading (30 points)",
					],
					is_group: false,
					event_status: true,
					latitude: "22 N",
					longitude: "66 E",
					score: 1,
				},
				{
					id: 38,
					genre: "Fine Arts",
					name: "Finger Dab",
					tagline: "Finger Painting Competition",
					writeup:
						"Immerse yourself in a realm of limitless creativity in our exciting finger painting competition! Set aside the brushes and let your fingers take the lead as you express yourself on canvas. Demonstrate your tactile artistry, blend colors with skill, and craft captivating artworks using the most basic tool—your fingers!",
					min_participation: 1,
					max_participation: 1,
					rules: [
						"",
						"1.This is an individual event.",
						"2.Participants are needed to make a painting based on a theme given to them \non the spot.",
						"3.Participants are strictly prohibited to use brushes or anything in place of fingers to paint.",
						"4.All logistics shall be provided on the spot. NO additional logistics apart from \nthose provided in the beginning, can be used.",
						"5.Use of any outside aids and internet is strictly prohibited and may lead to disqualification.",
					],
					is_group: false,
					event_status: true,
					latitude: "22 N",
					longitude: "66 E",
					score: 1,
				},
				{
					id: 39,
					genre: "Fine Arts",
					name: "Junk Art",
					tagline: "Waste Art Competition",
					writeup:
						"Turn waste into masterpieces in our eco-friendly waste art competition! Celebrate sustainability and creativity by transforming discarded materials into beautiful, one-of-a-kind art pieces.",
					min_participation: 1,
					max_participation: 2,
					rules: [
						"",
						"1. This is an individual event. Registrations will be accepted on the spot.",
						"2. The event will be conducted in one round.",
						"3. Participants are needed to make a craft work out of the given logistics at the time of the event.",
						"4. All logistics shall be provided on the spot. No additional logistics apart from those provided in the beginning can be used.",
						"5. Use of any outside aids and the internet is strictly prohibited and may lead to disqualification.",
						"6. JUDGING CRITERIA:\n\nCreativity and Innovation (40 points)\nEffective Use of Materials (30 points)\nOverall Impact and Message (30 points)",
					],
					is_group: false,
					event_status: true,
					latitude: "22 N",
					longitude: "66 E",
					score: 1,
				},
				{
					id: 40,
					genre: "Fine Arts",
					name: "Paint It",
					tagline: "Water Color Painting Competition ",
					writeup:
						"Dive into the enchanting world of watercolors and let your imagination flow onto the canvas.Express your artistic vision experiment with vibrant hues, and create stunning masterpieces that showcase your distinctive style.",
					min_participation: 1,
					max_participation: 1,
					rules: [
						"",
						"1. This is an individual event. Registrations will be accepted on the spot.",
						"2. The event will be conducted in one round.",
						"3. Participants are needed to make a painting based on a theme given to them on the spot.",
						"4. Basic necessary logistics have to be carried by the participants themselves.Additional Logistics will be provided at the venue.",
						"5. Use of any outside aids and the internet is strictly prohibited and may lead to disqualification.\n\nJudging Criteria: \n\nTechnique and Skill (35 points) \n\nComposition and Components (35 points)\n\nColour Harmony and Visual Impact (30 points)",
					],
					is_group: false,
					event_status: true,
					latitude: "22 N",
					longitude: "66 E",
					score: 1,
				},
				{
					id: 41,
					genre: "Fine Arts",
					name: "Rangoli",
					tagline: "Rangoli Making Competition",
					writeup:
						"Unleash your creativity in our one-of-a-kind soap carving competition! Master the delicate art of sculpting soap into intricate designs. Display your carving skills, precision ,and imaginative flair in a fun competition that highlights the beauty of art and craftsmanship.",
					min_participation: 1,
					max_participation: 3,
					rules: [
						"",
						"1. This is a team event.On-spot registrations will be accepted.",
						"2. Participating teams are needed to make a Rangoli based on a theme given on the spot.",
						"3. The size of each Rangoli should be 3ftX 3ft.",
						"4. There must NOT be any personal indication mark or writing on the job submitted.",
						"5. All logistics shall be provided on the spot. NO additional logistics apart from\nthose provided in the beginning can be used.",
						"6. Use of any outside aids and the internet is strictly prohibited and may lead to\ndisqualification.",
						"7. Judging criteria:\n\nCreativity and Design (40 points)\nTechnical Execution and Precision (30 points)\nOverall Presentation and Neatness (30 points)",
					],
					is_group: true,
					event_status: true,
					latitude: "22 N",
					longitude: "66 E",
					score: 1,
				},
				{
					id: 35,
					genre: "Fine Arts",
					name: "Bran-D",
					tagline: "Digital Branding Designing Competition",
					writeup:
						"Leverage the power of technology and design to craft visually striking brand identities. Create logos,visuals, and brand elements that connect with audiences and make a memorable impression\n",
					min_participation: 2,
					max_participation: 5,
					rules: [
						"",
						"1.SUBMISSION DEADLINE: 19th January,",
						"2025.",
						"2.SUBMISSION FORMAT: Mail your entry at finearts.sf2025@gmail.com with the subject “Bran-D:<Team Name>, <College Name>” in .jpeg or .tiff or .png format only.",
						"3.The opportunity will be listed on Unstop (Dare2Compete) platform.",
						"4.The problem statement shall be released one month before the fest.",
						"5.Participating teams shall decide the brand name according to the problem statement.",
						"5.The submission portfolio must necessarily consist of the following: \n• Corporate Logo • Corporate Tagline/Slogan • Corporate Logistics: Letter Head (21.59 cm x",
						"27.94 cm), Envelope (22 cm x 11cm), Business Card (9 cm x 5 cm), Email Signature, Stationery.",
						"6.For the final round, the team needs to prepare and present a Marketing Strategy for promoting and launching the brand for a period of 6 months, defining the media platforms used and the content and activity on each platform.",
						"7.Presentation must include: • Company name: whom you are • A literal descriptor slide: what you do • Tag line and values of the brand: how you do it • Unique company logo: your visual mark •Brand guide: your brand standards and Other designs • Marketing Campaigns: your marketing strategies and corporate branding strategies.",
						"8.In the final round at the campus, there should be at least 2 spokespeople and 1 person to handle the technical support.\n\nJudging Criteria: \n\nBrand Concept and Creativity (40 points)\n\nTechnical Execution and Brand Representation (30 points)\n\nOverall Presentation and Brand Impact (30 points)",
					],
					is_group: true,
					event_status: true,
					latitude: "22 N",
					longitude: "66 E",
					score: 1,
				},
				{
					id: 36,
					genre: "Fine Arts",
					name: "Digital Illustration",
					tagline: "Digital Art Competition",
					writeup:
						"Harness the power of technology to craft stunning digital artworks that challenge the limits of creativity. Join us to showcase your digital expertise, innovative ideas, and artistic vision using advanced software tools.",
					min_participation: 1,
					max_participation: 1,
					rules: [
						"",
						"1. This is an individual event. Registrations will be accepted on the spot.",
						"2. The event will be conducted in one round.",
						"3. Entries must be created digitally. Any software and tool can be used to create the illustrations.",
						"4. Themes will be released and informed 1 month before the fest.",
						"5. Entries must be original and created solely by the participant. Plagiarism or use of copyrighted materials should be strictly prohibited.",
						"6. Spring Fest will have all rights to use or display the artwork beyond the competition.",
						"7. SUBMISSION DEADLINE: 19th January,",
						"2025.",
						"8. SUBMISSION FORMAT: Upload your entries on Unstop platform with the name “Digital Illustration:<Participant Name>, <SFID>”.",
						"9. JUDING CRITERIA:\n\nArtistic Creativity and Originality (40 points)\n\nTechnical Skill and Execution (30 points)\n\nOverall Presentation and Impact (30 points)",
					],
					is_group: false,
					event_status: true,
					latitude: "22 N",
					longitude: "66 E",
					score: 1,
				},
				{
					id: 37,
					genre: "Fine Arts",
					name: "Face Canvas",
					tagline: "Face Painting Competition",
					writeup:
						"Step into a world of colors, brushes, and creativity as you transform the human face into a canvas for stunning art. Display your talent, unleash your artistic flair, and turn faces into mesmerizing masterpieces.",
					min_participation: 2,
					max_participation: 2,
					rules: [
						"",
						"1.This is a team event. Each team Will have 2 members. One member will paint on the other member's face.",
						"2.Participating teams can depict any theme but the use of the internet and external aid is strictly prohibited.",
						"3.Time limit for the event is 2 hours.",
						"4.Stickers and any kind of make-up items are not allowed.",
						"5.All logistics shall be provided on the spot. NO additional logistics apart from those provided in the beginning, can be used.\nJudging criteria includes:\n\nArtistic Creativity and Originality (40 points)\n\nTechnical Skill and Precision (30 points)\n\nOverall Presentation and Impact (30 points)",
					],
					is_group: true,
					event_status: true,
					latitude: "22 N",
					longitude: "66 E",
					score: 1,
				},
				{
					id: 43,
					genre: "Fine Arts",
					name: "Soapaholic",
					tagline: "Soap Carving Competition",
					writeup:
						"Unleash your creativity in our one-of-a-kind soap carving competition! Master the delicate art of sculpting soap into intricate designs. Display your carving skills, precision and imaginative flair in a fun competition that highlights the beauty of art and craftsmanship.",
					min_participation: 1,
					max_participation: 1,
					rules: [
						"",
						"1. This is an individual event. Registrations Will be accepted on the spot.",
						"2. Participating teams are needed to carve a soap based on any theme.",
						"3. The participants would be given only one bar of soap. They have to design on the same bar that is provided.",
						"4. All logistics shall be provided on the spot. NO additional logistics apart from\nthose provided in the beginning can be used.",
						"5. Use Of any outside aids and the internet is strictly prohibited and\nmay lead to disqualification.",
						"6. Judging criteria:\n\nCreativity and Design (40 points)\n\nTechnical Skill and Precision (30 points)\n\nOverall Presentation (30 points)",
					],
					is_group: false,
					event_status: true,
					latitude: "22 N",
					longitude: "66 E",
					score: 1,
				},
			],
		},
		{
			genre: "Humor Fest",
			events: [
				{
					id: 60,
					genre: "Humor Fest",
					name: "Banter Bout",
					tagline: "Improv Battle",
					writeup:
						"Gear up for the ultimate showdown of quick wit and spontaneity in our electrifying improv battle! Join us for a thrilling event filled with hilarious scenarios and on-the-spot creativity. Engage in a battle of wits, humor, and quick thinking, competing against fellow improv enthusiasts to deliver the most uproarious and unpredictable performances.",
					min_participation: 1,
					max_participation: 1,
					rules: [
						"",
						"1. This is a solo event.",
						"2. Certain rounds of distinct improv games will be conducted.",
						"3. Each game will be a separate eliminatory round and the judges will shortlist participants from each round to declare the final winner",
						"4. The games to be conducted will be chosen on the spot by the Judge(s).",
						"5. Time limits - if any - will be specified by the judges and appropriate penalty will be provided.",
						"6. Obscenity is left to judges' discretion.",
						"7. Judges’ decisions are final and binding.",
					],
					is_group: false,
					event_status: true,
					latitude: "22 N",
					longitude: "66 E",
					score: 1,
				},
				{
					id: 44,
					genre: "Humor Fest",
					name: "Hilarity Ensues",
					tagline: "Stand Up Comedy",
					writeup:
						"Step into the spotlight and bring on the laughs in our uproarious stand-up comedy competition,showcase your comedic genius, wit, and storytelling skills in front of a lively audience. Compete among budding comedians to deliver the most side-splitting performances and be crowned as the ultimate stand-up comedy champion!",
					min_participation: 1,
					max_participation: 1,
					rules: [
						"1. This is an individual event and participants will need to perform in Hindi or English or both.",
						"2. The time limit for the performance is of 5 minutes, exceeding which by 1 minute will lead to disqualification",
						"3. Any sort of racist, sexist or offensive slurs will lead to immediate disqualification",
						"4. Judging criteria includes:\n A. Content and creativity (40 points)\n B. Delivery and Stage Presence (30 points)\n C. Audience Engagement and Overall Impact (30 points)\n The judges' collective scores across these categories will determine the final outcome of the competition.",
					],
					is_group: false,
					event_status: true,
					latitude: "22 N",
					longitude: "66 E",
					score: 1,
				},
			],
		},
		{
			genre: "Fashion",
			events: [
				{
					id: 50,
					genre: "Fashion",
					name: "Navyata",
					tagline: "Fashion Show Competition",
					writeup:
						"Embrace the spotlight and unleash your creativity as you present your trendsetting designs to an eager audience. Join us for a dazzling display of haute couture and innovation, where fashion meets artistry, and showcase your talent to make a statement on the ramp like never before!",
					min_participation: 4,
					max_participation: 20,
					rules: [
						"",
						"1. Teams will be presenting a ramp walk on the day of the event on the pre-submitted audio.",
						"2. Judging will be done on an overall basis, including costumes, hairstyle and accessories.",
						"3. Teams may choreograph their walk and select a background music.",
						"4. Stunts which pose any risk to life are not permitted.",
						"5. Using any substance (or prop) that poses danger or might alter the stage in any way for the next team is not allowed (e.g. spilling of liquid that will affect the dryness).",
						"6. The teams will be expected to restore the stage to its original condition within the set time limit in case any prop or substance that causes temporary changes is used.",
						"7. Vulgarity is not allowed. Obscenity will left to judges’ discretion, and their decision will be final and binding in case any part of the performance is found objectionable.",
						"8. JUDING CRITERIA:\n\n• Ramp Walk (40 points)\n\n• Costume (30 points)\n\n• Stage Appearance (30 points)",
					],
					is_group: true,
					event_status: true,
					latitude: "22 N",
					longitude: "66 E",
					score: 1,
				},
				{
					id: 49,
					genre: "Fashion",
					name: "Mr and Ms SPRING FEST",
					tagline: "Personality Hunt Competition",
					writeup:
						"Step into the spotlight and let your charisma shine in our thrilling personality hunt competition! Showcase your unique charm, wit, and talent as you engage in a series of exciting challenges that celebrate individuality and confidence.\n",
					min_participation: 1,
					max_participation: 1,
					rules: [
						"",
						"1. The campus round will be an Introductory (Time limit – 2 minutes maximum) and Q&A round.",
						"2. All rules and questions shall be decided by the judges on the spot.",
						"3. Dress Code: For Boys – Blazer, Tie and dress slacks or a suit with shoes For Girls – Cocktail dress.",
						"4.JUDGING CRITERIA:\n\n• Introduction (40 points)\n\n• QnA Responses (30 points)\n\n• Adaptability and Versatility (30 points)",
					],
					is_group: false,
					event_status: true,
					latitude: "22 N",
					longitude: "66 E",
					score: 1,
				},
				{
					id: 51,
					genre: "Fashion",
					name: "Panache",
					tagline: "Paper Dress Designing Competition",
					writeup:
						"Spring Fest’s very own fashion show where flamboyance and design sense meet in an impromptu manner. The unique event witnesses dresses made out of paper designed on spot to suit the rigour and grace of the wearer. So run wild your imagination and create a masterpiece worth watching.",
					min_participation: 2,
					max_participation: 2,
					rules: [
						"",
						"1. This is a team event. Each team Will have 2 members, one member for whom the outfit will be designed and the other member who will design the outfit.",
						"2. Participating teams are needed to make a dress from the logistics provided to them on the spot. Newspapers, A4 sheets, Ribbons, scissor, stapler, pins, and cello tape will be given to each team.",
						"3. No additional logistics apart from the ones provided, can be used.",
						"4. Each team will have to give a presentation before the judges after the dress designing is over.",
						"5. Any potentially vulgar designing of the dress will lead to disqualification.",
						"6. Use of any outside aids and internet is strictly prohibited and may lead to disqualification\n\nJUDING CRITERIA:\n\n• Creativity and Originality (40 points)\n\n• Craftsmanship and Construction (30 points)\n\n• Aesthetic Appeal and Presentation (30 points)",
					],
					is_group: true,
					event_status: true,
					latitude: "22 N",
					longitude: "66 E",
					score: 1,
				},
				{
					id: 52,
					genre: "Fashion",
					name: "Peek A Who",
					tagline: "Cosplay Competition ",
					writeup:
						"Dive into the realm of creativity and bring your favorite personas to life with intricate costumes and attention to detail. Join us in celebrating fandoms and geek culture as you embody characters from various universes, showcase your craftsmanship, and immerse yourself in a world of fantasy and imagination, creating memorable moments that resonate with fellow enthusiasts and judges alike!",
					min_participation: 1,
					max_participation: 1,
					rules: [
						"",
						"1. This is a solo event.",
						"2. Costumes must be based on characters from published works, including movies, TV shows, comic books, cartoons, video games, and card games. Original interpretations are also accepted.",
						"3. Contestants must handle their costumes or have handlers present to assist them. Handlers must be registered attendees of the convention.",
						"4. Contestants are not allowed to throw anything off the stage, use projectiles, or create a mess.",
						"5. No pyrotechnics, fire, explosive devices, live animals, or similar special effects are allowed.",
						"6. Microphones are only available for live singing, poetry reading, and stand-up comedy acts.\n\nJUDGING CRITERIA:\n\n• Costume Craftsmanship (40 points)\n\n• Character Portrayal (30 points)\n\n• Originality and Creativity (30 points)",
					],
					is_group: false,
					event_status: true,
					latitude: "22 N",
					longitude: "66 E",
					score: 1,
				},
			],
		},
		{
			genre: "Game Fest",
			events: [
				{
					id: 53,
					genre: "Game Fest",
					name: "Labyrinth",
					tagline: "Labyrinth",
					writeup: "Labyrinth",
					min_participation: 2,
					max_participation: 5,
					rules: ["Labyrinth\nRules"],
					is_group: true,
					event_status: false,
					latitude: "22 N",
					longitude: "66 E",
					score: 1,
				},
			],
		},
		{
			genre: "Culinary Arts",
			events: [
				{
					id: 47,
					genre: "Culinary Arts",
					name: "Mixology",
					tagline: "Mocktail Making Competition",
					writeup:
						"Blend, shake, and stir your way to perfection in our exciting mocktail mixing competition! Display your bartending expertise, creative flavor pairings, and eye-catching presentations as you craft irresistible non-alcoholic beverages.",
					min_participation: 1,
					max_participation: 1,
					rules: [
						"",
						"1. This is an individual event. Registrations will be accepted on the spot if slots are available.",
						"2. The event will be conducted in one round.",
						"3. All materials and logistics will be provided by the judges on the spot.",
						"4. Participants have to prepare the mocktail on the spot within the given time limit.",
						"5. The decision of the judge will be binding and final.",
						"6. Participants should reach the venue on time. Spring Fest will not be responsible in case of late entry.",
						"7. The time limit is 10 minutes.",
						"8.JUDGING CRITERIA:\n\n• Creativity in Recipe and Presentation (40 points)\n\n• Flavour and Balance (30 points)\n\n• Technique and Execution (30 points).",
					],
					is_group: false,
					event_status: true,
					latitude: "22 N",
					longitude: "66 E",
					score: 1,
				},
				{
					id: 46,
					genre: "Culinary Arts",
					name: "Food Carving",
					tagline: "Food Competition",
					writeup:
						"Unleash your inner artist and let your creativity flow with Food Carving, the ultimate platform to showcase the extraordinary art of crafting beauty out of food. With nothing but skill, imagination, and a sharp eye for detail, participants will transform everyday fruits, vegetables, and more into mesmerizing creations.",
					min_participation: 1,
					max_participation: 1,
					rules: [
						"",
						"1.Click at least 3 photos of the final dish from multiple angles(Front view, top  view, Sideview, etc.) It should include the name of dish, ingredients, recipe, and  whether the recipe is self- made or not.",
						"2.Click 1 photo of a bite-size portion as well.",
						"3.Record a video of at least 2 minute showing the most crucial step of your cooking process.",
						"4.Write the recipe of the dish in a document and save it in .pdf format.",
					],
					is_group: true,
					event_status: false,
					latitude: "22 N",
					longitude: "66 E",
					score: 1,
				},
				{
					id: 45,
					genre: "Culinary Arts",
					name: "Chef's Corner",
					tagline: "Cooking Competition",
					writeup:
						"Ignite your passion for culinary artistry in our thrilling cooking competition! Step into the kitchen and demonstrate your skills, creativity, and expertise as you craft mouthwatering dishes within a limited time.",
					min_participation: 1,
					max_participation: 1,
					rules: [
						"",
						"1. This is an individual event. Registrations will be accepted on the spot if slots are available.",
						"2.The event will be conducted in one round.",
						"3.All materials and logistics will be provided by the judges on the spot.",
						"4..Participants have to prepare a dish within the given time limit.",
						"5. The decision of the judge will be binding and final.",
						"6. .Partcipants should reach the venue on time. Spring Fest will not be responsible in case of late entry.",
						"7.JUDGING CRITERIA:\n\n• Taste and Flavour (40 points)\n\n• Presentation and Plating (30 points)\n\n• Creativity and Innovation (30 points).",
					],
					is_group: false,
					event_status: true,
					latitude: "22 N",
					longitude: "66 E",
					score: 1,
				},
				{
					id: 48,
					genre: "Culinary Arts",
					name: "Top It to Win It",
					tagline: "Cupcake Dressing Competition",
					writeup:
						"Unleash your creativity and frosting finesse in our enchanting cupcake decorating competition! Showcase your artistic talent, attention to detail, and imaginative designs as you turn simple cupcakes into stunning edible masterpieces.\n",
					min_participation: 1,
					max_participation: 1,
					rules: [
						"",
						"1. This is an individual event. Registrations will be accepted on the spot if slots are available.",
						"2. The event will be conducted in one round.",
						"3. All materials and logistics will be provided by the judges on the spot.",
						"4. Participants have to decorate the cupcake on the spot within the given time limit.",
						"5. The decision of the judge will be binding and final.",
						"6. Participants should reach the venue on time. Spring Fest will not be responsible in case of late entry.",
						"7. The time limit is 30 minutes.",
						"8.JUDGING CRITERIA:\n\n• Creativity in Decoration (40 points)\n\n• Presentation and Aesthetic Appeal (30 points)\n\n• Taste and Texture (30 points).",
					],
					is_group: false,
					event_status: true,
					latitude: "22 N",
					longitude: "66 E",
					score: 1,
				},
			],
		},
	],
};

export default details;